# Ejercicios Numpy II

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [1]:
import numpy as np

In [8]:
my_array = np.arange(0,10)
print(my_array,"\n")

my_array[-1:0:-2]

[0 1 2 3 4 5 6 7 8 9] 



array([9, 7, 5, 3, 1])

## Ejercicio 2
Imprime por pantalla la secuencia [[8 7]] del array `my_array`

In [9]:
my_array[-2:-4:-1]

array([8, 7])

## Ejercicio 3
Imprime por pantalla la secuencia [[2 1 0]] de `my_array`

In [10]:
my_array[2::-1]

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [31]:
# 1. Crea una matriz de 4x5, con una secuencia del 1 al 20
matriz = np.arange(1,21)
matriz4x5 = matriz.reshape(4,5)
print(matriz4x5,"\n")
# 2. Invierte totalmente la matriz. Tanto las filas, como las columnas
print(matriz4x5[::-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 

[[16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [34]:
matriz4x5[0:2, 0:2]

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [36]:
matriz4x5[0:4:2, 0:5:2]

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [59]:
ejer7 = matriz4x5[0:3]

np.flip(ejer7, axis=1)

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [65]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
# 1 Filtrado con booleans

animal = x == "Loro"

print(x[animal])


['Loro' 'Loro']


In [72]:
# 2 Filtrado con condicionales

print(np.where(x == "Loro", x,""))      

['Loro' '' '' 'Loro' '']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [75]:
ejer9 = np.arange(0,20)
ejer9.reshape(2, 5,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del **ejercicio 4**
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [81]:
# matriz del ejercicio 4: 
print(matriz4x5,"\n")

np.flip(matriz4x5)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 



array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [105]:
ceros = np.zeros(10)
print(ceros)

ceros.itemsize


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


8

## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [106]:
vect = np.arange(10,50)
print(vect)

vect[::-1]

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [[1,2,0,0,4,0]]. El output sería [[0, 1, 4]]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [128]:
vector = [1,2,0,0,4,0]

#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [111]:
ejer14 = np.random.randint(1, 20, (10,10))
print(ejer14)

print(np.min(ejer14))
print(np.max(ejer14))

[[18 13  2 17  7  6  1 13 15 17]
 [14  4  5 16  8  8  1  1 17 14]
 [ 5 10  9 13 14  8  9 14 12 16]
 [14 12  4  3  3  3 12 16 12 12]
 [19 15 14  1 19  1  6 10  1  5]
 [ 1 19  4  3 10  5  4 19 16 12]
 [15  9 14 13 10  8 14 11  9 15]
 [15  8 11 13 12 12 15  4 14  5]
 [ 5 16 13 14 14  2 13 10  3  1]
 [19 12 10 19 15  5  8  2  7  9]]
1
19


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [122]:
ejer15 = np.random.rand(30)

np.sum(ejer15)/30

0.5889857776359596

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [184]:
np.ones((6,6))
np.zeros((6,6))
np.full((6,6),1)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

## Ejercicio 17
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [190]:
np.ones((1,8))
np.zeros((1,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.]])

## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [163]:
ejer13 = np.array([[0,1],[1,0]])
np.tile(ejer13,(4,4))


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

## Ejercicio 21 
#### Bonus track. Mini hundir la flota para ir practicando.
##### Te ayudará a entender la lógica de la tarea Hundir la Flota.
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.